### PR TITLE
renamed vent to actuator

### PR DESCRIPTION
**Pull request by sineadazam**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/38)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looks good, the only mention of vent I see is twice on the pcb silkscreen.

**Review by BluCodeGH — APPROVED** [review]
LGTM! @zx100x100 might want you to bump the board version and date but I'm not sure if it's necessary for a non-functional change.

**Review by zx100x100 — CHANGES_REQUESTED** [review]
Overall good work!

one tiny thing: looks like when you changed the silkscreen you bumped some of the text so it overlaps a solder pad. aside from fixing that, looks good!
image

**Review by zx100x100 — APPROVED** [review]
All looks good! :partyparrot:

**Review by QuantumManiac — APPROVED** [review]

**Pull request merged**
