### PR TITLE
Rename project to remote arming.

### PR DESCRIPTION
**Pull request by zx100x100**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/32)

### CODE REVIEW

**Review by LanaTomlin — APPROVED** [review]
Looks good to me.

**Review by QuantumManiac — APPROVED** [review]
Sorry for the delay! Everything looks good to me.

**Review by dwkletke — COMMENTED** [review]
> Reviewed 1 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/32)* status: 1 of 28 files reviewed, 1 unresolved discussion (waiting on @AidanHa, @dwkletke, @JaredWatson, @wendi-yu, @ZTeper, and @zx100x100)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/canhw/32#-MLAaJ1jBIuPPI9tjPtk:-MLAaJ1kEMkR8g7_H_Af:bephkbb) (no related file):*
Looks pretty good to me. Can you remind me why there is a separate `power.pro` project? That shouldn't be necessary right?

---

**Comment by zx100x100** [comment]
> > Reviewed 1 of 28 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/32)_ status: 1 of 28 files reviewed, 1 unresolved discussion (waiting on @AidanHa, @dwkletke, @JaredWatson, @wendi-yu, @ZTeper, and @zx100x100)
> 
> _[a discussion](https://reviewable.io/reviews/waterloo-rocketry/canhw/32#-MLAaJ1jBIuPPI9tjPtk:-MLAaJ1kEMkR8g7_H_Af:bephkbb) (no related file):_
> Looks pretty good to me. Can you remind me why there is a separate `power.pro` project? That shouldn't be necessary right?

oh yeah, that doesn't need to be there, removed.

**Review by dwkletke — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/32#-:-MN911ff0c-WG9hWwHMM:bnfp4nl)* status: 1 of 28 files reviewed, 1 unresolved discussion (waiting on @AidanHa, @dwkletke, @JaredWatson, @wendi-yu, and @ZTeper)

**Pull request merged**
