### PR TITLE
voltage divider changed

### PR DESCRIPTION
**Pull request by Lucifersan**
I just changed the resistor dividers

### CODE REVIEW

**Review by AshTheEngiqueer — CHANGES_REQUESTED** [review]
Where are changes? assuming you're talking about the divider on the +BATT voltage sensing line?

**Comment by Lucifersan** [comment]
yes, because with the old divider, if the 24V line shorted to the batt line it would send like 12V to the pic, which is not great. Now if 24V line shorts to bat or VCC it doesnt matter and the pic gets 5V input anyways. we lose a some fidelity this way but at the rate we've been killing pics on this board, I think that is an acceptable sacrifice to make.

**Review by AshTheEngiqueer — APPROVED** [review]

**Review by Joe-Joe-Joe-Joe — APPROVED** [review]
LGTM

**Review by Joe-Joe-Joe-Joe — CHANGES_REQUESTED** [review]
oops
just realized you did not regen the schematic PDF
that would be bad

**Review by ManavToor — APPROVED** [review]

**Comment by Lucifersan** [comment]
pdf regenerated

**Review by Joe-Joe-Joe-Joe — APPROVED** [review]
lgtm

**Review by Pdada1 — APPROVED** [review]

**Review by BluCodeGH — APPROVED** [review]

**Pull request merged**
