### PR TITLE
USB Debug Respin

### PR DESCRIPTION
**Pull request by BluCodeGH**
Adds silkscreen labels to CAN connector and an optional terminating resistor. Yes I know the trace hops are ugly but I don't want to reroute more than I already have.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/42)

### CODE REVIEW

**Review by QuantumManiac — APPROVED** [review]
LGTM. Update schematic PDF once everything is good to go pls.

Quick google search says that the resistor should be 120 Ohms and because I don't know any better, I'll take your word for it.

Before and after pics because it was helpful for me:
PCB:
- Front
image
image
- Back
image
image




Schematic:
image
image

**Review by zx100x100 — CHANGES_REQUESTED** [review]
Looks good, only thing is it would be nice to have labels on the jumpers so you can tell which is which

**Review by rdakhil — APPROVED** [review]
Looks good to me!

**Review by Artem-Sotnikov — APPROVED** [review]
Overall, lgtm. 

A few notes:
- Making the text point all in the same direction could be a good idea, especially since the board is not particularly tight on space
- Maybe on some of the more sensitive signals, stitching the ground planes might be a general good practice sort of thing. Although, this may be my emf noise paranoia speaking.

**Review by zx100x100 — APPROVED** [review]
:lg::tm:

**Pull request merged**
