### PR TITLE
Vent v2.1 

### PR DESCRIPTION
**Pull request by zx100x100**
Increase Trace width for better current carrying capabilities and add jumpers for drawing actuator power from the CAN bus.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/35)

### CODE REVIEW

**Comment by MattiGen** [comment]
image
You have this massive trace that branches into a tiny one at a 90 degree angle. Thats all I got for comments.

**Comment by zx100x100** [comment]
> image
> You have this massive trace that branches into a tiny one at a 90 degree angle. Thats all I got for comments.

Is this an issue? this is because it's a sensing line

**Comment by MattiGen** [comment]
> > image
> > You have this massive trace that branches into a tiny one at a 90 degree angle. Thats all I got for comments.
> 
> Is this an issue? this is because it's a sensing line

I just found it odd that it breaks off into becoming so tiny but if you say theres no issue then its probably fine.

**Review by LanaTomlin — APPROVED** [review]
I'm not super well-versed in this project, but it looks great to me. Alas, I might have found some daisy chaining?
image

**Comment by zx100x100** [comment]
this is acceptable since it is the current amp.

**Review by dwkletke — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/35#-:-MU4uubb4Ph14BW606vK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AidanHa, @JaredWatson, @MattiGen, and @QuantumManiac)

**Review by MattiGen — APPROVED** [review]

**Review by QuantumManiac — APPROVED** [review]
Is it okay to have this right-angle here? 
image

If so, then LGTM!

**Pull request merged**
