### PR TITLE
Fix CAN pins

### PR DESCRIPTION
**Pull request by wendi-yu**
CAN used to be set to pins A1 and A2, which don't support CAN. Switched it so that CAN is now on pins C0 and C1, and HALL_8 and HALL_7 are on pins A1 and A2 (which support IOC). I think I did it right but like I have no idea :^)

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/36)

### CODE REVIEW

**Review by BluCodeGH — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/36#-:-MXP0lMn4z3GdPte9Agw:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zx100x100)

**Review by BluCodeGH — APPROVED** [review]
Good catch!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/36#-:-MXP2SezCsrTh1PoOxTL:b6zrrk4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zx100x100)

**Review by dwkletke — COMMENTED** [review]
Changes look great! Just a little nitpick, there is a floating wire on the schematic:
image

**Comment by wendi-yu** [comment]
good catch tyty, fixed :0

**Review by dwkletke — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/36#-:-MXYa5Q60Kgb1JoSudeq:bnfp4nl)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @BluCodeGH, @JaredWatson, @MattiGen, and @zx100x100)

**Review by zx100x100 — CHANGES_REQUESTED** [review]
Looks like DRC comes up with a couple issues. (GND pad disconnected, trace overlapping unrelated pad.)

Also, still need to update the silkscreen date, add version to the name so it's obviously different hardware, and feel free to tack your name on the board as well.

should be quick fixes, plz include gerbers in next commit. :fantasticstuff:

**Review by zx100x100 — APPROVED** [review]
Looks awesome :partyparrot:

**Pull request merged**
