### PR TITLE
Fix voltage divider resistor values on LTT

### PR DESCRIPTION
**Pull request by BluCodeGH**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/49)

### CODE REVIEW

**Comment by dwkletke** [comment]
@BluCodeGH  Can you clarify what is being changed here? I don't see any difference between resistor values... But I might be blind 😅

**Comment by dwkletke** [comment]
> @BluCodeGH Can you clarify what is being changed here? I don't see any difference between resistor values... But I might be blind 😅

Was using the wrong kicad version... My bad 😄

**Review by dwkletke — APPROVED** [review]
Technically the comment stating the range of the divider's output voltage is _slightly_ outdated (0-2.031V) but you can update that if you'd like.

**Comment by Rio6** [comment]
closing this as ltt got a new revision and I dont think this applies anymore

**Pull request closed without merging**
