### PR TITLE
2024 cleanup

### PR DESCRIPTION
**Pull request by JasonBrave**

### CODE REVIEW

**Review by ManavToor — CHANGES_REQUESTED** [review]
keep logger

**Review by ManavToor — APPROVED** [review]

**Comment by Rio6** [comment]
why are we removing harwin footprints and 3d models?

**Comment by JasonBrave** [comment]
Because they got migrated to here because there are other repo need some of the footprints https://github.com/waterloo-rocketry/kicad-footprints

**Review by Rio6 — APPROVED** [review]
LGTM we can always get it back if we need something

**Review by miles-milne — APPROVED** [review]
Looks good to me. Happy that symbols/footprints are being moved to a git submodule.

**Pull request merged**
