### PR TITLE
Vibration Board (Actually for ordering)

### PR DESCRIPTION
**Pull request by IshmanM**
New PR because can't re-open the merged one.
Test Points for power are added and new gerbers made.

### CODE REVIEW

**Comment by Rio6** [comment]
圖片

J7 looks a bit too close to the programming connector, is there enough space to solder both?

圖片

Why does pin 10 here need to go around like this?

LGTM otherwise

**Comment by IshmanM** [comment]
@Rio6 
Thanks for the comments. I separated the header and cleaned up that gnd connection.

To anyone viewing this branch:
Jason helped me resolve some weird merge conflicts, hence all the commits. Gerbers addressing Rio's comments should be up now.

**Review by Joe-Joe-Joe-Joe — APPROVED** [review]
Your silkscreen is a month out of date. Other than that, LGTM.

**Review by AshTheEngiqueer — APPROVED** [review]
LGTM :)

**Review by ManavToor — APPROVED** [review]
You can just barely squeeze this silkscreen on the other side of the connector, I would move it over
image

Other than that, I couldn't find any issues with the board

**Review by JasonBrave — APPROVED** [review]
LGTM

**Pull request merged**
