### PR TITLE
Add v6 lib format and TCAN1042 transciever

### PR DESCRIPTION
**Pull request by Joe-Joe-Joe-Joe**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/50)

### CODE REVIEW

**Review by rdakhil — APPROVED** [review]
Symbol looks good to me

**Comment by Artem-Sotnikov** [comment]
Symbol looks good but by gods do we need that v6 library format. Let's merge it already.

**Review by Artem-Sotnikov — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/50)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Joe-Joe-Joe-Joe)

**Comment by Artem-Sotnikov** [comment]
The old library files only take up a couple of kB (a fraction of the size of a single PCB). Perhaps we should just move them to an 'archive' folder? That way of some old stuff has to be reference people wouldn't need to go into the archive of git history in order to find it.

**Comment by BluCodeGH** [comment]
Yeah sure. My goal is to intentionally break things to force people to update to the new library when they make revisions.

**Review by BluCodeGH — APPROVED** [review]

**Review by Joe-Joe-Joe-Joe — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/50)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Joe-Joe-Joe-Joe)

**Review by Joe-Joe-Joe-Joe — COMMENTED** [review]
:lgtm: 

I dont like Reviewable.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canhw/50#-:-NK4AUx5-OUx6kFbtEb4:b-qnk1es)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Joe-Joe-Joe-Joe)

**Pull request merged**
